/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUeRouteImport } from './routes/_app/ue'
import { Route as AppStagesRouteImport } from './routes/_app/stages'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSemestresRouteImport } from './routes/_app/semestres'
import { Route as AppPresencesRouteImport } from './routes/_app/presences'
import { Route as AppMatieresRouteImport } from './routes/_app/matieres'
import { Route as AppInscriptionsRouteImport } from './routes/_app/inscriptions'
import { Route as AppGroupesRouteImport } from './routes/_app/groupes'
import { Route as AppFilieresRouteImport } from './routes/_app/filieres'
import { Route as AppEnseignantsRouteImport } from './routes/_app/enseignants'
import { Route as AppDepartementsRouteImport } from './routes/_app/departements'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnneesRouteImport } from './routes/_app/annees'
import { Route as AppAffectationsRouteImport } from './routes/_app/affectations'
import { Route as AppNotesIndexRouteImport } from './routes/_app/notes.index'
import { Route as AppEtudiantsIndexRouteImport } from './routes/_app/etudiants.index'
import { Route as AppResultatsSemestreRouteImport } from './routes/_app/resultats.semestre'
import { Route as AppResultatsAnnuelRouteImport } from './routes/_app/resultats.annuel'
import { Route as AppReportsBulletinRouteImport } from './routes/_app/reports.bulletin'
import { Route as AppNotesSaisieRouteImport } from './routes/_app/notes.saisie'
import { Route as AppEtudiantsCreateRouteImport } from './routes/_app/etudiants.create'
import { Route as AppEtudiantsIdRouteImport } from './routes/_app/etudiants.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUeRoute = AppUeRouteImport.update({
  id: '/ue',
  path: '/ue',
  getParentRoute: () => AppRoute,
} as any)
const AppStagesRoute = AppStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSemestresRoute = AppSemestresRouteImport.update({
  id: '/semestres',
  path: '/semestres',
  getParentRoute: () => AppRoute,
} as any)
const AppPresencesRoute = AppPresencesRouteImport.update({
  id: '/presences',
  path: '/presences',
  getParentRoute: () => AppRoute,
} as any)
const AppMatieresRoute = AppMatieresRouteImport.update({
  id: '/matieres',
  path: '/matieres',
  getParentRoute: () => AppRoute,
} as any)
const AppInscriptionsRoute = AppInscriptionsRouteImport.update({
  id: '/inscriptions',
  path: '/inscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupesRoute = AppGroupesRouteImport.update({
  id: '/groupes',
  path: '/groupes',
  getParentRoute: () => AppRoute,
} as any)
const AppFilieresRoute = AppFilieresRouteImport.update({
  id: '/filieres',
  path: '/filieres',
  getParentRoute: () => AppRoute,
} as any)
const AppEnseignantsRoute = AppEnseignantsRouteImport.update({
  id: '/enseignants',
  path: '/enseignants',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartementsRoute = AppDepartementsRouteImport.update({
  id: '/departements',
  path: '/departements',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnneesRoute = AppAnneesRouteImport.update({
  id: '/annees',
  path: '/annees',
  getParentRoute: () => AppRoute,
} as any)
const AppAffectationsRoute = AppAffectationsRouteImport.update({
  id: '/affectations',
  path: '/affectations',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRoute,
} as any)
const AppEtudiantsIndexRoute = AppEtudiantsIndexRouteImport.update({
  id: '/etudiants/',
  path: '/etudiants/',
  getParentRoute: () => AppRoute,
} as any)
const AppResultatsSemestreRoute = AppResultatsSemestreRouteImport.update({
  id: '/resultats/semestre',
  path: '/resultats/semestre',
  getParentRoute: () => AppRoute,
} as any)
const AppResultatsAnnuelRoute = AppResultatsAnnuelRouteImport.update({
  id: '/resultats/annuel',
  path: '/resultats/annuel',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsBulletinRoute = AppReportsBulletinRouteImport.update({
  id: '/reports/bulletin',
  path: '/reports/bulletin',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesSaisieRoute = AppNotesSaisieRouteImport.update({
  id: '/notes/saisie',
  path: '/notes/saisie',
  getParentRoute: () => AppRoute,
} as any)
const AppEtudiantsCreateRoute = AppEtudiantsCreateRouteImport.update({
  id: '/etudiants/create',
  path: '/etudiants/create',
  getParentRoute: () => AppRoute,
} as any)
const AppEtudiantsIdRoute = AppEtudiantsIdRouteImport.update({
  id: '/etudiants/$id',
  path: '/etudiants/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/affectations': typeof AppAffectationsRoute
  '/annees': typeof AppAnneesRoute
  '/dashboard': typeof AppDashboardRoute
  '/departements': typeof AppDepartementsRoute
  '/enseignants': typeof AppEnseignantsRoute
  '/filieres': typeof AppFilieresRoute
  '/groupes': typeof AppGroupesRoute
  '/inscriptions': typeof AppInscriptionsRoute
  '/matieres': typeof AppMatieresRoute
  '/presences': typeof AppPresencesRoute
  '/semestres': typeof AppSemestresRoute
  '/settings': typeof AppSettingsRoute
  '/stages': typeof AppStagesRoute
  '/ue': typeof AppUeRoute
  '/etudiants/$id': typeof AppEtudiantsIdRoute
  '/etudiants/create': typeof AppEtudiantsCreateRoute
  '/notes/saisie': typeof AppNotesSaisieRoute
  '/reports/bulletin': typeof AppReportsBulletinRoute
  '/resultats/annuel': typeof AppResultatsAnnuelRoute
  '/resultats/semestre': typeof AppResultatsSemestreRoute
  '/etudiants/': typeof AppEtudiantsIndexRoute
  '/notes/': typeof AppNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/affectations': typeof AppAffectationsRoute
  '/annees': typeof AppAnneesRoute
  '/dashboard': typeof AppDashboardRoute
  '/departements': typeof AppDepartementsRoute
  '/enseignants': typeof AppEnseignantsRoute
  '/filieres': typeof AppFilieresRoute
  '/groupes': typeof AppGroupesRoute
  '/inscriptions': typeof AppInscriptionsRoute
  '/matieres': typeof AppMatieresRoute
  '/presences': typeof AppPresencesRoute
  '/semestres': typeof AppSemestresRoute
  '/settings': typeof AppSettingsRoute
  '/stages': typeof AppStagesRoute
  '/ue': typeof AppUeRoute
  '/etudiants/$id': typeof AppEtudiantsIdRoute
  '/etudiants/create': typeof AppEtudiantsCreateRoute
  '/notes/saisie': typeof AppNotesSaisieRoute
  '/reports/bulletin': typeof AppReportsBulletinRoute
  '/resultats/annuel': typeof AppResultatsAnnuelRoute
  '/resultats/semestre': typeof AppResultatsSemestreRoute
  '/etudiants': typeof AppEtudiantsIndexRoute
  '/notes': typeof AppNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/affectations': typeof AppAffectationsRoute
  '/_app/annees': typeof AppAnneesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departements': typeof AppDepartementsRoute
  '/_app/enseignants': typeof AppEnseignantsRoute
  '/_app/filieres': typeof AppFilieresRoute
  '/_app/groupes': typeof AppGroupesRoute
  '/_app/inscriptions': typeof AppInscriptionsRoute
  '/_app/matieres': typeof AppMatieresRoute
  '/_app/presences': typeof AppPresencesRoute
  '/_app/semestres': typeof AppSemestresRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stages': typeof AppStagesRoute
  '/_app/ue': typeof AppUeRoute
  '/_app/etudiants/$id': typeof AppEtudiantsIdRoute
  '/_app/etudiants/create': typeof AppEtudiantsCreateRoute
  '/_app/notes/saisie': typeof AppNotesSaisieRoute
  '/_app/reports/bulletin': typeof AppReportsBulletinRoute
  '/_app/resultats/annuel': typeof AppResultatsAnnuelRoute
  '/_app/resultats/semestre': typeof AppResultatsSemestreRoute
  '/_app/etudiants/': typeof AppEtudiantsIndexRoute
  '/_app/notes/': typeof AppNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/affectations'
    | '/annees'
    | '/dashboard'
    | '/departements'
    | '/enseignants'
    | '/filieres'
    | '/groupes'
    | '/inscriptions'
    | '/matieres'
    | '/presences'
    | '/semestres'
    | '/settings'
    | '/stages'
    | '/ue'
    | '/etudiants/$id'
    | '/etudiants/create'
    | '/notes/saisie'
    | '/reports/bulletin'
    | '/resultats/annuel'
    | '/resultats/semestre'
    | '/etudiants/'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/affectations'
    | '/annees'
    | '/dashboard'
    | '/departements'
    | '/enseignants'
    | '/filieres'
    | '/groupes'
    | '/inscriptions'
    | '/matieres'
    | '/presences'
    | '/semestres'
    | '/settings'
    | '/stages'
    | '/ue'
    | '/etudiants/$id'
    | '/etudiants/create'
    | '/notes/saisie'
    | '/reports/bulletin'
    | '/resultats/annuel'
    | '/resultats/semestre'
    | '/etudiants'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/affectations'
    | '/_app/annees'
    | '/_app/dashboard'
    | '/_app/departements'
    | '/_app/enseignants'
    | '/_app/filieres'
    | '/_app/groupes'
    | '/_app/inscriptions'
    | '/_app/matieres'
    | '/_app/presences'
    | '/_app/semestres'
    | '/_app/settings'
    | '/_app/stages'
    | '/_app/ue'
    | '/_app/etudiants/$id'
    | '/_app/etudiants/create'
    | '/_app/notes/saisie'
    | '/_app/reports/bulletin'
    | '/_app/resultats/annuel'
    | '/_app/resultats/semestre'
    | '/_app/etudiants/'
    | '/_app/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ue': {
      id: '/_app/ue'
      path: '/ue'
      fullPath: '/ue'
      preLoaderRoute: typeof AppUeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stages': {
      id: '/_app/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof AppStagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/semestres': {
      id: '/_app/semestres'
      path: '/semestres'
      fullPath: '/semestres'
      preLoaderRoute: typeof AppSemestresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presences': {
      id: '/_app/presences'
      path: '/presences'
      fullPath: '/presences'
      preLoaderRoute: typeof AppPresencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matieres': {
      id: '/_app/matieres'
      path: '/matieres'
      fullPath: '/matieres'
      preLoaderRoute: typeof AppMatieresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inscriptions': {
      id: '/_app/inscriptions'
      path: '/inscriptions'
      fullPath: '/inscriptions'
      preLoaderRoute: typeof AppInscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groupes': {
      id: '/_app/groupes'
      path: '/groupes'
      fullPath: '/groupes'
      preLoaderRoute: typeof AppGroupesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/filieres': {
      id: '/_app/filieres'
      path: '/filieres'
      fullPath: '/filieres'
      preLoaderRoute: typeof AppFilieresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enseignants': {
      id: '/_app/enseignants'
      path: '/enseignants'
      fullPath: '/enseignants'
      preLoaderRoute: typeof AppEnseignantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departements': {
      id: '/_app/departements'
      path: '/departements'
      fullPath: '/departements'
      preLoaderRoute: typeof AppDepartementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/annees': {
      id: '/_app/annees'
      path: '/annees'
      fullPath: '/annees'
      preLoaderRoute: typeof AppAnneesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affectations': {
      id: '/_app/affectations'
      path: '/affectations'
      fullPath: '/affectations'
      preLoaderRoute: typeof AppAffectationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/etudiants/': {
      id: '/_app/etudiants/'
      path: '/etudiants'
      fullPath: '/etudiants/'
      preLoaderRoute: typeof AppEtudiantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resultats/semestre': {
      id: '/_app/resultats/semestre'
      path: '/resultats/semestre'
      fullPath: '/resultats/semestre'
      preLoaderRoute: typeof AppResultatsSemestreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resultats/annuel': {
      id: '/_app/resultats/annuel'
      path: '/resultats/annuel'
      fullPath: '/resultats/annuel'
      preLoaderRoute: typeof AppResultatsAnnuelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/bulletin': {
      id: '/_app/reports/bulletin'
      path: '/reports/bulletin'
      fullPath: '/reports/bulletin'
      preLoaderRoute: typeof AppReportsBulletinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/saisie': {
      id: '/_app/notes/saisie'
      path: '/notes/saisie'
      fullPath: '/notes/saisie'
      preLoaderRoute: typeof AppNotesSaisieRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/etudiants/create': {
      id: '/_app/etudiants/create'
      path: '/etudiants/create'
      fullPath: '/etudiants/create'
      preLoaderRoute: typeof AppEtudiantsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/etudiants/$id': {
      id: '/_app/etudiants/$id'
      path: '/etudiants/$id'
      fullPath: '/etudiants/$id'
      preLoaderRoute: typeof AppEtudiantsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAffectationsRoute: typeof AppAffectationsRoute
  AppAnneesRoute: typeof AppAnneesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartementsRoute: typeof AppDepartementsRoute
  AppEnseignantsRoute: typeof AppEnseignantsRoute
  AppFilieresRoute: typeof AppFilieresRoute
  AppGroupesRoute: typeof AppGroupesRoute
  AppInscriptionsRoute: typeof AppInscriptionsRoute
  AppMatieresRoute: typeof AppMatieresRoute
  AppPresencesRoute: typeof AppPresencesRoute
  AppSemestresRoute: typeof AppSemestresRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStagesRoute: typeof AppStagesRoute
  AppUeRoute: typeof AppUeRoute
  AppEtudiantsIdRoute: typeof AppEtudiantsIdRoute
  AppEtudiantsCreateRoute: typeof AppEtudiantsCreateRoute
  AppNotesSaisieRoute: typeof AppNotesSaisieRoute
  AppReportsBulletinRoute: typeof AppReportsBulletinRoute
  AppResultatsAnnuelRoute: typeof AppResultatsAnnuelRoute
  AppResultatsSemestreRoute: typeof AppResultatsSemestreRoute
  AppEtudiantsIndexRoute: typeof AppEtudiantsIndexRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAffectationsRoute: AppAffectationsRoute,
  AppAnneesRoute: AppAnneesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartementsRoute: AppDepartementsRoute,
  AppEnseignantsRoute: AppEnseignantsRoute,
  AppFilieresRoute: AppFilieresRoute,
  AppGroupesRoute: AppGroupesRoute,
  AppInscriptionsRoute: AppInscriptionsRoute,
  AppMatieresRoute: AppMatieresRoute,
  AppPresencesRoute: AppPresencesRoute,
  AppSemestresRoute: AppSemestresRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStagesRoute: AppStagesRoute,
  AppUeRoute: AppUeRoute,
  AppEtudiantsIdRoute: AppEtudiantsIdRoute,
  AppEtudiantsCreateRoute: AppEtudiantsCreateRoute,
  AppNotesSaisieRoute: AppNotesSaisieRoute,
  AppReportsBulletinRoute: AppReportsBulletinRoute,
  AppResultatsAnnuelRoute: AppResultatsAnnuelRoute,
  AppResultatsSemestreRoute: AppResultatsSemestreRoute,
  AppEtudiantsIndexRoute: AppEtudiantsIndexRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
